name: AndroidBuild

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'

  pull_request:
      types: [ opened, reopened, synchronize ]
  release:
      types: [ published ]

jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: '<distribution>'
          java-version: '17'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run : ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Fridgey_FoodTracker.apk
          path: app/build/outputs/apk/debug/Fridgey_FoodTracker.apk
